name: rockclient_dart
description: Rockclient Dart
version: 1.0.0
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  skawa_material_components: ^1.1.0+1
  skawa_components: ^1.1.0
  angular_router: ^2.0.0-alpha+21
  firebase: ^5.0.0
  tuple: ^1.0.2
  sass_builder: ^2.1.3
dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.6.5
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  #pageloader: ^3.2.0
  test: ^1.6.3
